### ISSUE TITLE
Navigation buttons vanish from ipad two column view

### ISSUE THREAD

**Issue by PeterGracar** [robotswingset/narwhal-bugs#77]
**Describe the bug**
When rotating the iPad and making the app the app alternate between two column mode and one column mode, the navigation buttons in the first column vanish.

**To Reproduce**
1. Go to subreddit in two column mode and open post.
2. Rotate ipad to portrait so that single column mode engages (app might have to be in windowed mode to be narrow enough). The post/comments should be shown as a result. 
3. Rotate iPad back to trigger two column mode. 
4. Buttons in first column are gone

**Expected behavior**
Buttons should not disappear

**Screenshots**
[Before](https://www.icloud.com/iclouddrive/078149AZN1L349hvYczqcRAHw#IMG_0034)
[After](https://www.icloud.com/iclouddrive/0e4usO4lVKOQMN4H28STakYIQ#IMG_0035)
[Video](https://www.icloud.com/iclouddrive/045DSX_esOCAn1cN3JIZSH0JQ#ScreenRecording_10-02-2025_23-25-49_1)

**Device Information:**
 - Device: iPad m4 13 inch
 - OS: iPadOS 26.0.1
 - Version 2025.8.1

**Comment by rickharrison** [comment]
I think this is fixed in iPadOS 26.2 - Can you try updating?

**Comment by PeterGracar** [comment]
Unfortunately it is not fixed - here's a recording from 26.2: [video](https://www.icloud.com/iclouddrive/02bJpYBHdUpfTQnIUASVfDofA#ScreenRecording_12-11-2025_12-05-06_1)
